# Generated by Django 5.2.12 on 2026-03-14 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(default='1337 School', max_length=255)),
                ('start_time', models.CharField(default='22:00', max_length=5)),
                ('end_time', models.CharField(default='06:00', max_length=5)),
                ('overnight', models.BooleanField(default=True)),
                ('active_days', models.JSONField(default=list)),
                ('frequency_minutes', models.IntegerField(default=60)),
                ('buses', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StoppedPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopped_periods', to='schedules.scheduleconfig')),
            ],
        ),
    ]
